#!/bin/bash
# install symbolic links to the scripts in /usr/local/bin

DEST=/usr/local/bin
HERE="$(dirname "$(readlink -f "$0")")"

for x in my-update my-snaps my-restore my-snaps-cronjob homed-update; do
    sudo rm -f "$DEST/$x"
    (set -x; sudo ln -s "$HERE/$x" "$DEST/$x")
done
